name: Fetch Issues

on:
  workflow_dispatch: # 手動トリガー

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Issuesを取得（ページング対応）
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        REPO="snakajima/life-is-beautiful"
        OUTPUT_FILE="issues.json"

        # ページングで全件取得
        PAGE=1
        RESULTS=()
        while :; do
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/issues?state=all&per_page=100&page=$PAGE")
          ITEMS=$(echo "$RESPONSE" | jq '. | length')
          if [ "$ITEMS" -eq 0 ]; then
            break
          fi
          RESULTS+=("$RESPONSE")
          PAGE=$((PAGE + 1))
        done

        # 全件をマージしてファイルに保存
        echo "${RESULTS[@]}" | jq -s 'add' > $OUTPUT_FILE

    - name: JSONをコミットしてPush
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add issues.json
        git commit -m "Update issues.json"
        git push
